## NAMA : FELIX CHRISTOPHER AFRIAN 
## NIM : 2109106049

# Mengimport Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
df = pd.read_csv("CO2 Emissions_Canada.csv")

# Informasi yang di-dapat dan dimasukkan dalam dictionary

In [12]:
info = {
  'total_records': 0,
  'attributes': [],
  'object_attributes': 0,
  'number_attributes': 0,
  'null_attributes': 0
}

info['total_records'] = df.shape[0]
info['attributes'] = list(df.columns.values)
info['null_attributes'] = list(df.loc[:, df.isnull().any()].columns)
info['object_attributes'] = list(df.select_dtypes(['object']).columns)
info['number_attributes'] = list(df.select_dtypes(['float64', 'int64']).columns)

# Jumlah Record

In [7]:
print ("Jumlah Record :", info['total_records'] )

Jumlah Record : 7385

# Nama dan Jumlah Atribut

In [10]:
print ("Nama-nama Attribute :", info['attributes'])
print ("Jumlah Attribute :", len(info['attributes']))

Nama-nama Attribute : ['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders', 'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)']
Jumlah Attribute : 12

# Jumlah Atribut dengan Tipe Objek

In [17]:
print ("Jumlah Atribut dengan Tipe Objek :", info['object_attributes'], len(info['object_attributes']))

Jumlah Atribut dengan Tipe Objek : ['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type'] 5

# Jumlah Atribut dengan Tipe Angka

In [19]:
print ("Jumlah Attribute dengan Tipe Angka :", info['number_attributes'], len(info['number_attributes']))

Jumlah Attribute dengan Tipe Angka : ['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'] 7

# Jumlah Atribut dengan Tipe Null

In [21]:
print ("Jumlah Attribute yang Memiliki Nilai Null :", info['null_attributes'], len(info['null_attributes']))

Jumlah Attribute yang Memiliki Nilai Null : [] 0

# Menampilkan RATA-RATA, STD, MIN, MAX, Q1, Q2, Q3

In [22]:
df.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

# Menampilkan Nilai Korelasi bertipe angka

In [23]:
df.corr()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
Engine Size(L),1.000000,0.927653,0.831379,0.761526,0.817060,-0.757854,0.851145
Cylinders,0.927653,1.000000,0.800702,0.715252,0.780534,-0.719321,0.832644
Fuel Consumption City (L/100 km),0.831379,0.800702,1.000000,0.948180,0.993810,-0.927059,0.919592
Fuel Consumption Hwy (L/100 km),0.761526,0.715252,0.948180,1.000000,0.977299,-0.890638,0.883536
Fuel Consumption Comb (L/100 km),0.817060,0.780534,0.993810,0.977299,1.000000,-0.925576,0.918052
Fuel Consumption Comb (mpg),-0.757854,-0.719321,-0.927059,-0.890638,-0.925576,1.000000,-0.907426
CO2 Emissions(g/km),0.851145,0.832644,0.919592,0.883536,0.918052,-0.907426,1.000000

# Mengubah atribut menjadi desimal

## Sebelum "Cylinder" diubah

In [32]:
df.dtypes

Make                                 object
Model                                object
Vehicle Class                        object
Engine Size(L)                      float64
Cylinders                             int64
Transmission                         object
Fuel Type                            object
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

In [33]:
df['Cylinders'] = df['Cylinders'].astype('float64')

## Sesudah "Cylinder" diubah

In [26]:
df.head(10)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4.0,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4.0,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4.0,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6.0,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6.0,AS6,Z,12.1,8.7,10.6,27,244
5,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.0,28,230
6,ACURA,TL,MID-SIZE,3.5,6.0,AS6,Z,11.8,8.1,10.1,28,232
7,ACURA,TL AWD,MID-SIZE,3.7,6.0,AS6,Z,12.8,9.0,11.1,25,255
8,ACURA,TL AWD,MID-SIZE,3.7,6.0,M6,Z,13.4,9.5,11.6,24,267
9,ACURA,TSX,COMPACT,2.4,4.0,AS5,Z,10.6,7.5,9.2,31,212

In [34]:
df.dtypes

Make                                 object
Model                                object
Vehicle Class                        object
Engine Size(L)                      float64
Cylinders                           float64
Transmission                         object
Fuel Type                            object
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

# Menampilkan 10 record pertama Atribut angka

In [35]:
dh = df.select_dtypes(include=np.number)
dh.head(10)

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4.0,9.9,6.7,8.5,33,196
1,2.4,4.0,11.2,7.7,9.6,29,221
2,1.5,4.0,6.0,5.8,5.9,48,136
3,3.5,6.0,12.7,9.1,11.1,25,255
4,3.5,6.0,12.1,8.7,10.6,27,244
5,3.5,6.0,11.9,7.7,10.0,28,230
6,3.5,6.0,11.8,8.1,10.1,28,232
7,3.7,6.0,12.8,9.0,11.1,25,255
8,3.7,6.0,13.4,9.5,11.6,24,267
9,2.4,4.0,10.6,7.5,9.2,31,212

# Menyimpan dataset bertipe angka ke csv

In [38]:
df[['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)']].to_csv("data_angka.csv")